package fr.insa.projetIntegrateur.UserService.model;

import java.util.ArrayList;
import java.util.List;

public final class Profile {
	//-------------------------------- FIELDS --------------------------------//

	//the ids mean something and arent autogenerated!!
	private static int idProfile;
	private static String profileName;
	
	//fixed profiles values
	//TO MODIFY WITH ACTUAL VALUES!!!!!
	private final List<Float> DEFAULT = new ArrayList<>();
	private final List<Float> SPEED = new ArrayList<>();
	private final List<Float> SAFETY = new ArrayList<>();
	private final List<Float> COMFORT = new ArrayList<>();
	
	//-------------------------------- CONSTRUCTORS --------------------------------//
	
	public Profile() {
	}

	//-------------------------------- GETTERS/SETTERS --------------------------------//
	
	public int getIdProfile() {
		return idProfile;
	}

	public String getProfileName() {
		return profileName;
	}
	
	//-------------------------------- METHODS --------------------------------//

	//returns the weights for a fixed user profile necessary for the routing computation
	public List<Float> getWeights(int idProfile) {
		switch (idProfile) {
			case 0:
				return DEFAULT;
			case 1:
				return SPEED;
			case 2:
				return SAFETY;
			case 3:
				return COMFORT;
			default:
				return new ArrayList<>();
		}
	}
}
