package fr.insa.projetIntegrateur.UserService.model;

import java.util.ArrayList;
import java.util.List;

public final class Profile {
	//-------------------------------- FIELDS --------------------------------//

	//the ids mean something and arent autogenerated!!
	private static int idProfile;
	private static String profileName;
	private static String profileVector;
	
	//fixed profiles values
	//TO MODIFY WITH ACTUAL VALUES!!!!!
	private final String DEFAULT = "";
	private final String SPEED = "";
	private final String SAFETY = "";
	private final String COMFORT = "";
	
	//-------------------------------- CONSTRUCTORS --------------------------------//
	
	public Profile() {
	}

	//-------------------------------- GETTERS/SETTERS --------------------------------//
	
	public int getIdProfile() {
		return idProfile;
	}
	
	public int setIdProfile(int idProfile) {
		return this.idProfile = idProfile;
	}
	

	public String getProfileName() {
		return profileName;
	}
	
	public String setProfileName(String profileName) {
		return this.profileName = profileName;
	}
	
	public String getProfileVector() {
		return profileVector;
	}
	
	public String setProfileVector(String profileVector) {
		return this.profileVector = profileVector;
	}
	
}
