spring.application.name=GatewayService
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8889}
#server.port=8081

# ==============================
#   CONFIGURATION MYSQL
# ==============================

spring.datasource.url=jdbc:mysql://srv-bdens.insa-toulouse.fr:3306/projet_gei_040
spring.datasource.username=projet_gei_040
spring.datasource.password=iesaey6U
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.cloud.config.enabled=false