# Port 8761 is the standard for Eureka servers
server.port=8761

# Tell Eureka NOT to register itself as a client
eureka.client.register-with-eureka=false

# Tell Eureka NOT to fetch the registry from other servers
eureka.client.fetch-registry=false